[package]
name = "users"
version = "0.1.0"
authors = ["Roberts Kalnins <robertsmkalnins@gmail.com>"]
edition = "2018"

[dependencies]
colored = "1.7"
prettytable-rs = "^0.8"
serde = { version = "1.0.90", features = ["derive"] }
serde_json = "1.0"